### ISSUE TITLE
Training environments?

### ISSUE THREAD

**Issue by sunlex0717** [NM-sparsity/NM-sparsity#1]
Congratulations for the great ICLR2021 work!

I would like to test your codes and try to reproduce resnet18 results.

Could you provide some details about which/how many GPUs you used for getting the results?

Thanks!

**Comment by AojunZhou** [comment]
@sunlex0717 hi,

thanks for your appreciation!,  8 Titan XP GPUs with batch size 256.

**Comment by AojunZhou** [comment]
other parameters refer to https://github.com/NM-sparsity/NM-sparsity/blob/main/classification/configs/config_resnet50_2by4.yaml
