### ISSUE TITLE
Config file for classification

### ISSUE THREAD

**Issue by priyankaankolekar** [NM-sparsity/NM-sparsity#10]
Hi, 
I am trying to reproduce the results from this repo. The config file has:

    train_root: /mnt/lustre/share/images/train
    train_source: /mnt/lustre/share/images/meta/train.txt
    val_root: /mnt/lustre/share/images/val
    val_source: /mnt/lustre/share/images/meta/val.txt

From what I understand, 
train_root == path where the training images are located.
val_root == path where the validation images are located.
train_source == Where in the imagenet downloads can I find this file?
val_source == Where in the imagenet downloads can I find this file?

Thanks,
Priyanka.

**Comment by aojunzz** [comment]
@priyankaankolekar hi, 

you can refer to https://drive.google.com/drive/folders/1BL0IOrI0fUcTrRwtMObH5xLB1-ySLT32?usp=sharing

**Comment by priyankaankolekar** [comment]
Thanks a lot. This is very helpful.
