### ISSUE TITLE
Zero weights in trained model

### ISSUE THREAD

**Issue by qlou** [NM-sparsity/NM-sparsity#12]
Hay authors,
Thank you so much for sharing the code. It helps a lot for us to understand the structured sparsity.

I downloaded the model file for the classification networks to look at the weights using the code below. 

import torch
model = torch.load('resnet50_1_4.pth', map_location="cpu")
print(model['state_dict']['layer3.2.conv2.weight'])

However, I didn't find there are zero weights in the pre-trained network. I was wondering whether I miss anything here.

Thanks,
qlou

**Comment by aojunzz** [comment]
@qlou thanks for your question, the checkpoint keep the dense weight, but you can see 50% sparsity when using the sparseConv during the forward.

Thanks,

Aojun
