### ISSUE TITLE
About the STE

### ISSUE THREAD

**Issue by hustzxd** [NM-sparsity/NM-sparsity#13]
Thanks for your insightful work.
However, I still have some confusion about whether to compute the gradients of the masked weights.

For example, 
```python 
return grad_output + ctx.decay * (1-ctx.mask) * weight, None, None
```
computes the gradient of the masked weight.

```python 
return grad_output * ctx.mask + ctx.decay * (1-ctx.mask) * weight, None, None
```
does not compute the gradient of the masked weight.

I think the masked weights have no connection to the final loss and their gradients should be zeros.

Is there a reasonable explanation here to choose the first or the second one?

Thank you.

**Comment by aojunzz** [comment]
@hustzxd Thanks for your appreciation, 

Q1: the masked weights (zero) should not be zeros. You can print the gradients of masked weights.

Q2: the first update scheme is to add the refined term on the gradients of masked weights, the gradients will be accumulated during the training. If you choose the second, it only adds the regularization term on original random weights. 

Besides, if masked weights are recovered during training, the first scheme have better initialization than second one.

**Comment by hustzxd** [comment]
Thanks for your reply. I got it.
