### ISSUE TITLE
Lack `bias` in the forward process of   `SparseLinear`

### ISSUE THREAD

**Issue by lz02k** [NM-sparsity/NM-sparsity#14]
https://github.com/NM-sparsity/NM-sparsity/blob/main/devkit/sparse_ops/sparse_ops.py#L107 

Should add  'self.bias' in the forward process of   `SparseLinear`?

@NM-sparsity

**Comment by aojunzz** [comment]
@lz02k yes, if you use the SparseLinear without the BN layer, you should add self.bias in the forward.
