### ISSUE TITLE
Resnet experiment settings 

### ISSUE THREAD

**Issue by ilil96** [NM-sparsity/NM-sparsity#2]
Thanks for open-sourcing such a cool work.
I am now trying to reproduce your resnet50 results.
Table 3 in the paper implies that you sparsified also the first and the last layer for SR-STE result. There is no * mark on SR-STE result and the parameter count is exactly reduced by the sparsity factor. 

However your code (classification/models/resnet.py) seems to keep the last fc layer dense. It seems to use vanilla Linear module instead of the sparse one. 
Could you please clarify this issue?

Thanks!

**Comment by aojunzz** [comment]
@ilil96 thanks for your appreciation, 

Yes, we keep the last FC layer dense, Before Nvidia ASP.sparsity released, we have run the experiments and only sparsified all Conv layers. * mark the first layer keep dense. We will clarify this point in the revised version. Sorry for the confusion.

Our colleague re-implement the resnet50 using our method, config and results are as follows:

16GPUs batch_size(1k) epochs(100) coslr_nesterov  weight_decay(0.00005): 76.7(Top1)  93.3(top5).
