### ISSUE TITLE
Resnet model zoo

### ISSUE THREAD

**Issue by ilil96** [NM-sparsity/NM-sparsity#3]
Hi,
The pth file downloaded from the google drive link in the image classification model zoo does not match the description.
Only two files (dense.pth / resnet50(2:4)) are on the links and even these two files seem to be same. 
I would appreciate if you settle this issue.

Thanks.

**Comment by AojunZhou** [comment]
Hi, we don't release the other model.  BTW, you can contact me by email at aojunzhou@gmail.com

**Comment by AojunZhou** [comment]
@ilil96
