### ISSUE TITLE
where can i get the file meta/train.txt and meta/val.txt ? thanks

### ISSUE THREAD

**Issue by codeman-24** [NM-sparsity/NM-sparsity#5]

**Comment by aojunzz** [comment]
@zhushibing please refer to https://github.com/BVLC/caffe/blob/master/data/ilsvrc12/get_ilsvrc_aux.sh

**Comment by codeman-24** [comment]
> @zhushibing please refer to https://github.com/BVLC/caffe/blob/master/data/ilsvrc12/get_ilsvrc_aux.sh

Thanks again!

**Comment by wangwz6666** [comment]
学长nb
