### ISSUE TITLE
How to reproduce the profiler info in the provided log?

### ISSUE THREAD

**Issue by fantasysee** [NM-sparsity/NM-sparsity#6]
I really appreciate the authors for doing such an inspiring job and sharing the code.

I checked the log provided in the repo and found there is profiler information.
When I reproduced the result, I found there isn't in my log.
Would you please share how to obtain the profiler info below?

```
I0411 14:15:26.218456 19631 MemcachedClient.cpp:1027] average hit ratio is 99.78 %
I0411 14:15:26.218978 19631 MemcachedClient.cpp:1028] num_hits is: 9978 num_reads is: 10000
I0411 14:15:26.218986 19631 MemcachedClient.cpp:1029] average elapsed time in fetching get connection is 0.0011917 ms
I0411 14:15:26.218994 19631 MemcachedClient.cpp:1030] average elapsed time in getting value from cache is 0.318302 ms
I0411 14:15:26.219000 19631 MemcachedClient.cpp:1031] average elapsed time in getting value from DFS is 26.9152 ms
I0411 14:15:26.219007 19631 MemcachedClient.cpp:1032] average elapsed time in fetching put connection is 0 ms
I0411 14:15:26.219010 19631 MemcachedClient.cpp:1033] average elapsed time in putting value in cache is 0 ms
```

Thanks in advance!!!

**Comment by aojunzz** [comment]
@fantasysee 
Thanks for your appreciation!

Because we used an internal dataloader tool to speed up the process of loading data in SenseTime, the tool cannot be released. But the tool doesn't influence the performance.

**Comment by fantasysee** [comment]
OK, I see. Thank you for your warmful reply!!!
