### ISSUE TITLE
resnet50 dense model 

### ISSUE THREAD

**Issue by wangwz6666** [NM-sparsity/NM-sparsity#7]
Is the accuracy of  resnet50 dense model averaged many times? The results of my several experiments in dense were very different, respectively 77.696、77.376、77.36、77.296。

**Comment by NM-sparsity** [comment]
No, we don't run the dense model many times.

**Comment by aojunzz** [comment]
@wangwz6666 No, we don't run the dense model many times.

**Comment by wangwz6666** [comment]
So what do you think about dense models that fluctuate so much?

**Comment by aojunzz** [comment]
@wangwz6666 I am not sure the reasons why the dense models fluctuate.

**Comment by wangwz6666** [comment]
Can the results of this paper prove the effectiveness of SRSTE?

**Comment by aojunzz** [comment]
@wangwz6666 of course, you can run the SR-STE and STE experiments by yourself, BTW, our NeurIPS2021 paper DominoSearch even can achieve better accuracy than SOTA unstructured sparsity. You can refer to  https://papers.nips.cc/paper/2021/file/ad68473a64305626a27c32a5408552d7-Paper.pdf
