### ISSUE TITLE
ColorAugmentation

### ISSUE THREAD

**Issue by CYang0515** [NM-sparsity/NM-sparsity#8]
Thanks for open-sourcing such a cool work. I  have a confusion that why the [ColorAugmentation](https://github.com/NM-sparsity/NM-sparsity/blob/bd350d1260cf5fa5d3543bd64605891ec6736c84/devkit/dataset/imagenet_dataset.py#L39) is differnt from [mmclassification](https://github.com/open-mmlab/mmclassification/blob/6beac5060f0c1d57141642dba77c19c9ed6b3873/mmcls/datasets/pipelines/transforms.py#L994) and [mmcv](https://github.com/open-mmlab/mmcv/blob/4fb59b9830a880e5962e6cf43b9c57738867f712/mmcv/image/photometric.py#L373)? Specially, the eig_vec and reduction direction are reversed?

**Comment by aojunzz** [comment]
@CYang0515 hi, the classification task did not implement based on mmclassification, we don't need to follow the mmcv and mmclassification setting.
