### ISSUE TITLE
SparseConv for the first conv?

### ISSUE THREAD

**Issue by CYang0515** [NM-sparsity/NM-sparsity#9]
The [SparseConv](https://github.com/NM-sparsity/NM-sparsity/blob/bd350d1260cf5fa5d3543bd64605891ec6736c84/devkit/sparse_ops/sparse_ops.py#L18) splits weight into group. However, for the fisrt conv in resnet, the filter dims are 3 * 7 * 7 that is not evenly divided by 4, so the group will cross filter. Is this practical?

**Comment by aojunzz** [comment]
Yes, if you want to deploy the sparse model on Nvidia ampere GPUs, the first layer of resnet50 should be kept dense, you can refer to the nvidia.asp setting, asp kept the first layer dense. for 2:4 sparsity, the sparse or dense first layer have little influence on accuracy.
